name: Deploy KarateHub

on:
  push:
    paths:
      - 'karate-source/**'
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Install and Build 🔧
        run: |
          cd karate-source
          npm install
          npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: karate-source/dist # The folder the action should deploy.
          target-folder: karate # The folder in the branch to deploy to.
          branch: main # Deploy directly back to the main branch's karate folder
